# syntax=docker/dockerfile:1

# Use Ubuntu base image
FROM ubuntu:24.04

LABEL maintainer="devmichalek@gmail.com"

# Install build dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        curl \
        build-essential \
        pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install rustup a command line tool for managing Rust version and associated tools
RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
#RUN rustup update

# Setup group and user
ARG USER_ID=1001
ARG GROUP_ID=1001
ARG USER_NAME=juser
ARG GROUP_NAME=jgroup
RUN groupadd -o -r $GROUP_NAME --gid=$GROUP_ID
RUN useradd -o -r -g $GROUP_NAME --uid=$USER_ID --shell=/bin/bash --create-home $USER_NAME
WORKDIR /home/$USER_NAME

# Copy application sources
COPY --chown=$USER_NAME:$GROUP_ID app/ /home/$USER_NAME/app/
COPY --chown=$USER_NAME:$GROUP_ID Makefile /home/$USER_NAME/Makefile

# Switch to user account
USER $USER_NAME
