.PHONY: build-debug
build-debug:
	cargo build

.PHONY: run-debug
run-debug:
	cargo run

.PHONY: build-release
build-release:
	cargo build --release

.PHONY: run-release
run-release:
	cargo run --release
